version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      - image: tutum/mongodb
        command: [--name, buckets_db, -p, 27017:27017, -p, 28017:28017, -e, MONGODB_USER=username , -e MONGODB_DATABASE=buckets_test,  -e,  MONGODB_PASS=password , -e,  AUTH=no]
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "~/project/backend/package.json" }}{{checksum "~/project/frontend/package.json"}}

          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd ~/project/backend && yarn install
      - run: cd ~/project/frontend && yarn install

      - save_cache:
          paths:
            - ~/project/backend/node_modules
            - ~/project/frontend/node_modules
          key: dependencies-{{ checksum "~/project/backend/package.json" }}{{checksum "~/project/frontend/package.json"}}
        
      # run tests!
      - run: cd ~/project/backend && yarn test_server
      - run: cd ~/project/fontend && yarn test
      