version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "~/repo/backend/package.json" }}{{checksum "~/repo/frontend/package.json"}}

          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd ~/repo/backend && yarn install
      - run: cd ~/repo/frontend && yarn install

      - save_cache:
          paths:
            - ~/repo/backend/node_modules
            - ~/repo/frontend/node_modules
          key: dependencies-{{ checksum "~/repo/backend/package.json" }}{{checksum "~/repo/frontend/package.json"}}
        
      # run tests!
      - run: cd ~/repo/backend && yarn startDatabase && yarn test_server
      - run: cd ~/repo/fontend && yarn test
      